### ISSUE TITLE
Fix the `test_onpremise_datafileupdate_console` test

### ISSUE THREAD

**Issue by pi-alexander-popel** [51Degrees/device-detection-python#18]
[It's currently disabled](https://github.com/51Degrees/device-detection-python/blob/main/fiftyone_devicedetection_examples/tests/test_onpremiseexamples.py#L61), because it was always [timing out](https://github.com/51Degrees/device-detection-python/blob/main/fiftyone_devicedetection_examples/fiftyone_devicedetection_examples/onpremise/datafileupdate_console.py#L345).

**Comment by justadreamer** [comment]
done as part of #68
