### ISSUE TITLE
remove python 3.7, add python 3.12

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/device-detection-python#39]
According to https://endoflife.date/python - python 3.7 is not receiving security updates anymore, so it should be removed from options.json and instead 3.12 should be introduced.  Let's update the options.json runtime matrix for all python repos: 

- [x] https://github.com/51Degrees/pipeline-python
- [x] https://github.com/51Degrees/device-detection-python
- [x] https://github.com/51Degrees/location-python

**Comment by justadreamer** [comment]
@pi-alexander-popel please make this update  cc: @Sniperik

**Comment by pi-alexander-popel** [comment]
https://github.com/51Degrees/pipeline-python/pull/17
https://github.com/51Degrees/device-detection-python/pull/40
https://github.com/51Degrees/location-python/pull/9

**Comment by Sniperik** [comment]
This one is merged now and should be closed @justadreamer
